src/abcquotations/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcquotations.Domain.Entities;
using abcquotations.Service.Contract;
using abcquotations.Web.Filters.Securiry;
using abcquotations.Web.Helpers;
using abcquotations.Web.Models;
using AutoMapper;

namespace abcquotations.Web.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;
        private readonly IWayPayService _wayPayService;
        private readonly IUserService _userService;
        private readonly ITypeDocumentService _typeDocumentService;
        private readonly HelperProvider _helperProvider;
        private readonly HelperClient _helperClient;

        public ClientController(IClientService clientService, IWayPayService wayPayService, IContactService contactService, IUserService userService, ITypeDocumentService typeDocumentService)
        {
            _clientService = clientService;
            _helperProvider = new HelperProvider(wayPayService);
            _helperClient = new HelperClient(typeDocumentService);
            _userService = userService;
            
        }

        // GET: Client
        public ActionResult Index()
        {
            Mapper.Initialize(o => o.CreateMap<Client, ClientModel>());
            var clients = Mapper.Map<IEnumerable<Client>, List<ClientModel>>(_clientService.GetAll());
            return View(clients);
        }

        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Client/Create
        [AuthorizeRoles("Admin", "Editor")]
        public ActionResult Create()
        {
            ViewData["SelectListWayPay"] = _helperProvider.ListWayPays();
            ViewData["SelectListTipeDoc"] = _helperClient.SelectListTypeDocuments();
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        [AuthorizeRoles("Admin","Editor")]
        public ActionResult Create(ClientModel model, string[] selectedWayPay)
        {
            try
            {
                var currentUser = _userService.FindT(u => u.LoginName.Equals(User.Identity.Name));
                var client = new Client
                {
                    Consecutive = model.Consecutive,
                    IdTypeDocument = model.IdTypeDocument,
                    NumberDocument = model.NumberDocument,
                    RowCreatedDateTime = DateTime.Now,
                    RowCreatedSYSUserID = currentUser.Id,
                    Contact = new Contact
                    {
                        Name = model.NameContact,
                        Address = model.Address,
                        Phone = model.Phone,
                        Email = model.Email,
                        RowCreatedSYSUserID = currentUser.Id,
                        RowCreatedDateTime = DateTime.Now
                    }
                };

                _clientService.Add(client);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Client/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/abcquotations/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcquotations.Domain.Entities;
using abcquotations.Service.Contract;
using abcquotations.Web.Filters.Securiry;
using abcquotations.Web.Helpers;
using abcquotations.Web.Models;
using AutoMapper;

namespace abcquotations.Web.Controllers
{
    [Authorize]
    public class ProviderController : Controller
    {
        private readonly IProviderService _providerService;
        private readonly IContactService _contactService;
        private readonly IWayPayService _wayPayService;
        private readonly IUserService _userService;
        private readonly HelperProvider _helperProvider;

        public ProviderController(IProviderService providerService, IWayPayService wayPayService, IContactService contactService, IUserService userService)
        {
            _providerService = providerService;
            _helperProvider = new HelperProvider(wayPayService);
            _contactService = contactService;
            _userService = userService;
        }

        // GET: Provider
        public ActionResult Index()
        {
            Mapper.Initialize(o => o.CreateMap<Provider, ProviderModel>());
            var providers = Mapper.Map<IEnumerable<Provider>, List<ProviderModel>>(_providerService.GetAll());
            return View(providers);
        }

        // GET: Provider/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Provider/Create
        [AuthorizeRoles("Admin", "Editor")]
        public ActionResult Create()
        {
            ViewData["SelectListWayPay"] = _helperProvider.ListWayPays();
            return View();
        }

        // POST: Provider/Create
        [AuthorizeRoles("Admin","Editor")]
        [HttpPost]
        public ActionResult Create(ProviderModel model, string[] selectedWayPay)
        {
            try
            {
                var currentUser = _userService.FindT(u => u.LoginName.Equals(User.Identity.Name));
                var listWayPay = selectedWayPay.Select(item => new Provider_WayPay
                {
                    IdWayPay = Convert.ToInt32(item)
                }).ToList();

                var provider = new Provider
                {
                    Contact = new Contact
                    {
                        Name = model.NameContact,
                        Address = model.Address,
                        Phone = model.Phone,
                        Email = model.Email,
                        RowCreatedSYSUserID = currentUser.Id,
                        RowCreatedDateTime = DateTime.Now
                    },
                    Consecutive = model.Consecutive,
                    Name = model.Name,
                    RowCreatedDateTime = DateTime.Now,
                    RowCreatedSYSUserID = currentUser.Id
                };
                _providerService.Add(provider);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                var exep = ex.Message;
                return View();
            }
        }

        // GET: Provider/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Provider/Edit/5
        [HttpPost]
        [AuthorizeRoles("Admin", "Editor")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Provider/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Provider/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/abcquotations/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcquotations.Domain.Entities;
using abcquotations.Service.Contract;
using abcquotations.Web.Filters.Securiry;
using abcquotations.Web.Helpers;
using abcquotations.Web.Models;
using AutoMapper;

namespace abcquotations.Web.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        private readonly IUserService _serviceUser;
        private readonly IRoleService _serviceRole;
        private readonly AccountHelper _helper;

        public RoleController(IRoleService  serviceRole, IUserService userService, IGenderService genderService, IStateUserService stateUserService, IStatesRolesService statesRolesService)
        {
            _serviceUser = userService;
            _serviceRole = serviceRole;
            _helper = new AccountHelper(userService, serviceRole, genderService, stateUserService, statesRolesService);
        }
        // GET: Role
        public ActionResult Index()
        {
            Mapper.Initialize(o => o.CreateMap<Role, RoleModel>());
            var roles = Mapper.Map<IEnumerable<Role>, List<RoleModel>>(_serviceRole.GetAll());

            return View(roles);
        }

        // GET: Role/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Role/Create
        public ActionResult Create()
        {
            ViewData["SelectListStatesRole"] = _helper.SelectListStatesRoles();
            return View();
        }

        // POST: Role/Create
        [AuthorizeRoles("Admin")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var currentUser = _serviceUser.FindT(u => u.LoginName.Equals(User.Identity.Name));
                var newRole = new Role
                {
                    Name = collection["Name"],
                    Description = collection["Description"],
                    State = Convert.ToInt32(collection["State"]),
                    RowCreatedByUserID = currentUser.Id,
                    RowCreatedDateTime = DateTime.Now
                };

                _serviceRole.Add(newRole);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Role/Edit/5
        [AuthorizeRoles("Admin")]
        public ActionResult Edit(int id)
        {
            Mapper.Initialize(o => o.CreateMap<Role, RoleModel>());
            var role = Mapper.Map<Role, RoleModel>(_serviceRole.GetById(id));
            ViewData["SelectListStatesRole"] = _helper.SelectListStatesRoles();
            return View(role);
        }

        // POST: Role/Edit/5
        [AuthorizeRoles("Admin")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var currentUser = _serviceUser.FindT(u => u.LoginName.Equals(User.Identity.Name));
                var setRole = _serviceRole.GetById(Convert.ToInt32(collection["IdRole"]));
                setRole.Name = collection["Name"];
                setRole.Description = collection["Description"];
                setRole.State = Convert.ToInt32(collection["State"]);
                setRole.RowModifiedByUserID = currentUser.Id;
                setRole.RowModifiedDateTime = DateTime.Now;

                _serviceRole.Update(setRole);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Role/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Role/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/abcquotations/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using abcquotations.Domain.Entities;
using abcquotations.Service.Contract;
using abcquotations.Web.Filters.Securiry;
using abcquotations.Web.Helpers;
using abcquotations.Web.Models;
using AutoMapper;

namespace abcquotations.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _serviceUser;
        private readonly IRoleService _serviceRole;
        private readonly IGenderService _serviceGender;
        private readonly IStateUserService _serviceStateUser;
        private readonly IUserRoleService _userRoleService;
        private readonly IStatesRolesService _statesRolesService;
        private readonly AccountHelper _helper;
        private readonly UserHelper _userHelper;
        public UserController(IUserService userService, IRoleService roleService, IGenderService genderService, IStateUserService stateUserService, IUserRoleService userRoleService, IStatesRolesService statesRolesService)
        {
            _serviceUser = userService;
            _statesRolesService = statesRolesService;
            _helper = new AccountHelper(userService, roleService, genderService, stateUserService, statesRolesService);
            _userHelper = new UserHelper(userService, userRoleService);
            
        }
        // GET: User
        public ActionResult Index()
        {
            Mapper.Initialize(o => o.CreateMap<User, UserModel>());
            var users = Mapper.Map<IEnumerable<User>, List<UserModel>>(_serviceUser.GetAll());

            return View(users);
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        [AuthorizeRoles("Admin")]
        public ActionResult Edit(int id)
        {
            Mapper.Initialize(o => o.CreateMap<User, UserModel>());
            var userBd = _serviceUser.GetById(id);
            var user = Mapper.Map<User, UserModel>(userBd);
            ViewData["SelectCurrentRoles"] = userBd.UserRoles.ToList();
            ViewData["SelectListRoles"] = _helper.SelectListRoles();
            ViewData["SelectListStates"] = _helper.SelectListStatesUser();
            return View(user);
        }

        // POST: User/Edit/5
        [AuthorizeRoles("Admin")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var user = _userHelper.SetEditUser(collection);
                _serviceUser.Update(user);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/abcquotations/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
<div class="container">
    <header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    @Html.ActionLink("ABC Intercargo SAS", "Index", "Home")
                </div>
            </div>
            <div class="navbar-brand pull-right">
                <i class="glyphicon glyphicon-user"></i><a href="/">@Context.User.Identity.Name</a>
                @Html.ActionLink("Logout", "SignOut", "Account")
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse pull-right">
                @*<ul class="nav navbar-nav">
                        <li class="menu-item dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li class="menu-item dropdown dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">level 1</a>
                                    <ul class="dropdown-menu">
                                        <li class="menu-item ">
                                            <a href="#">Link 1</a>
                                        </li>
                                        <li class="menu-item dropdown dropdown-submenu">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Level 2</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#">Link 3</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>*@
                <ul class="nav navbar-nav">
                    <li class="menu-item dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="menu-item ">
                                @Html.ActionLink("Lista", "Index", "User")
                            </li>
                            <li class="menu-item ">
                                @Html.ActionLink("Crear", "NewUser", "Account")
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="menu-item dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Roles<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="menu-item ">
                                @Html.ActionLink("Lista", "Index", "Role")
                            </li>
                            <li class="menu-item ">
                                @Html.ActionLink("Crear", "Create", "Role")
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="menu-item dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Proveedor<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="menu-item ">
                                @Html.ActionLink("Lista", "index", "Provider")
                            </li>
                            <li class="menu-item ">
                                @Html.ActionLink("Crear", "Create", "Provider")
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="menu-item dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cliente<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="menu-item ">
                                @Html.ActionLink("Lista", "index", "Client")
                            </li>
                            <li class="menu-item ">
                                @Html.ActionLink("Crear", "Create", "Client")
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/common")
@RenderSection("scripts", required: false)
@RenderSection("MyScripts", required: false)
</body>
</html>